on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ['go1.1', 'go1.2', 'go1.3', 'go1.4', 'go1.5']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: make deps
    - run: go test -v -bench .
    - run: make examples